---
title: "The Last Lab Quiz!!"
author: "Katherine McAuley"
date: "November 22, 2016"
output: word_document
---
I examined the extent to which exam grades (E) were predicted by anxiety (A) and preparation (P). As indicated in Table 1, when the predictors were examined individually, there was a strong positive relation between anxiety and exam grades, *r*=.69, 95% CI[.64,.73], such that as anxiety increased exam grades also increased. Additionally there was a moderate to strong positive relation between preparation and exam grades, *r*=.49, 95% CI[.42,.56], such that as prepartion increased so did exam grades. 

I used moderated multiple regression to test the extent to which the relation between anxiety and exam grades depended on the amount of exam preparation. I assessed this moderation by examining the interaction between anxiety and preparation ususing centered predictors (consistent with the recommendations of Cohen, Cohen, West and Aiken (2003)), see Table 2. Together the predictors (anxiety, preparation, and their product) accounted for a substantial variance in exam grades, $R^2$=.62, 95% CI[.57,.66], *p*<.01. Results for the product term in this analysis were mixed. Specifically the p value for the anxiety by preparation product term was below .05, *t*(496) = 6.061, *p* < 0.0001, which suggests the presence of an interaction. However, an inspection of squared semi-partial correlation for the product term indicated the proportion of variance accounts for was small, $sr^2$ = .03 and the confidence interval overlapped with zero, 95% CI[.01,.05]. In light of this conflicting information regarding the presence of an interaction, I opted on the side of discovery and explored the regression surface with simple-slope analyses - though caution is needed when interpreting these findings. 

The regression surface is presented in Figure 1 and the simple-slope cross-sections are presented in Figure 2. When preparation is high (ie., +1SD) there was a positive relation between anxiety and exam grades, *b* = 19.49, 95% CI[17.50,21.48], *t*(496) = 19.26, *p*<.001, see Equation 1 below. When preparation was low (ie., -1SD), there was also a positive relation between anxiety and exam grade, *b* = 11.02, 95% CI[9.08,12.96], *t*(496) = 11.02, *p*<.001, see Equation 2 below. 

$/^{E}$ = 19.46A + 55.90 (1)
$/^{E}$ = 11.02 + 42.52 (2)

Thus the relation between anxiety and exam grades does not appear to be moderated by the extent to which students prepared for the exam. The relationship between anxiety and exam grades remains the same regardless of whether students extensively prepared or not.  